[workspace]
[package]
version = "0.1.0"
name = "option-pricer-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/0xkanekiken/sp1.git" }
serde = { version = "1.0.196", features = ["derive"] }
bincode = "1.3"
